POST http://localhost:3001/api/notes
content-type: application/json

{
  "content": "VSC rest client is op!",
  "important": true
}

###

POST http://localhost:3001/api/notes
content-type: application/json

{
  "content": "I'm a good programmer",
  "important": false
}

###
POST http://localhost:3001/api/notes 
content-type: application/json

{
"content": "VS code rest client is pretty handy tool", "important": true
}